services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=app_db_password
      - POSTGRES_DB=app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/redis
  worker:
    build: .
    depends_on:
        - redis
    command: rq worker --url redis://redis:6379 emails
    links:
        - redis
volumes:
  postgres_data:
  redis_data: